### ISSUE TITLE
Issue after setting everything up

### ISSUE THREAD

**Issue by cqmpact** [stroupbslayen/PUBG-Discord-Bot#1]
```
Ignoring exception in command stats
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\pcpla\source\repos\blu_bot\blu_bot\cogs\pubg.py", line 109, in stats
    data = await self.getID(player)
  File "C:\Users\pcpla\source\repos\blu_bot\blu_bot\cogs\pubg.py", line 69, in getID
    season=season['data-status']
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\bs4\element.py", line 1011, in __getitem__
    return self.attrs[key]
KeyError: 'data-status'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'data-status'

```

**Comment by cqmpact** [comment]
Fix found and posted:
https://github.com/stroupbslayen/PUBG-Discord-Bot/compare/master...cqmpact:patch-1
